version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENV_NAME: ${ENV_NAME}
    env_file: .env
    volumes:
      -  './src/:/home/src'
    ports:
      - ${APP_PORT}:${APP_PORT}

networks:
  default:
    name: alm-network
    external: True
